---
title: "Edit_a_project"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Edit_a_project}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ranglr)
```

Here I'll showcase useful functions when editing a projects

```{r get_uuids}
staging_submission_uuid <- "5cdbe23d64198100078914ea"
query_existing_submission(staging_submission_uuid, 
                          submission_environment = "staging", 
                          entity_type = "biomaterials")
```

```{r}
prod_submission_uuid <- "5d3b11bc9be88c0008a9d744"
#"f8aa201c-4ff1-45a4-890e-840d63459ca2"
#"8d2aace1-34d6-4c6c-bc4a-3af461dd7559"

query_existing_submission(prod_submission_uuid, 
                          submission_environment = "prod", 
                          entity_type = "protocols")
```

Can get the `Ingest Submission id` from the prod data tracker https://tracker.data.humancellatlas.org/
